const KEY='webefy_crm_v1';
const initial={role:'caller',user:{name:'Aman',role:'Sales Executive'},batch:{assigned:50,start:'2026-09-22',end:'2026-09-24'},leads:[
{id:'WF-001',business:'Sharma Appliances',contact:'Raj Sharma',phone:'9876543221',category:'Appliances',location:'Bhopal',status:'Qualified',followup:'',notes:'Owner interested; Webefy discussion completed.',sale:15000,payment:15000,commissionPaid:2250,created:'2026-09-22'},
{id:'WF-002',business:'Royal Cafe',contact:'Neha',phone:'9776543242',category:'Cafe',location:'Bhopal',status:'Follow-up',followup:'2026-09-25T17:00',notes:'Asked for website examples.',sale:0,payment:0,commissionPaid:0,created:'2026-09-22'},
{id:'WF-003',business:'Verma Motors',contact:'Amit Verma',phone:'8865432109',category:'Automobile',location:'Sehore',status:'New',followup:'',notes:'',sale:0,payment:0,commissionPaid:0,created:'2026-09-23'},
{id:'WF-004',business:'City Dental',contact:'Dr. Mehta',phone:'9165432173',category:'Clinic',location:'Bhopal',status:'Not Interested',followup:'',notes:'Already using another provider.',sale:0,payment:0,commissionPaid:0,created:'2026-09-23'},
{id:'WF-005',business:'Shree Fitness',contact:'Karan',phone:'9987654312',category:'Fitness',location:'Bhopal',status:'Qualified',followup:'',notes:'Wants pricing call.',sale:15000,payment:7500,commissionPaid:1125,created:'2026-09-23'},
{id:'WF-006',business:'Patel Interiors',contact:'Rohit Patel',phone:'9898123456',category:'Interiors',location:'Bhopal',status:'WhatsApp Details',followup:'',notes:'Details sent on WhatsApp.',sale:0,payment:0,commissionPaid:0,created:'2026-09-23'},
{id:'WF-007',business:'Maa Collection',contact:'Pooja',phone:'9123456700',category:'Retail',location:'Bhopal',status:'Follow-up',followup:'2026-09-25T12:00',notes:'Call after lunch.',sale:0,payment:0,commissionPaid:0,created:'2026-09-24'}
],activity:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||initial;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function commissionRate(){const q=state.leads.filter(l=>l.status==='Qualified').length;return q>=20?.20:q>=10?.15:.10}
function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function statusClass(s){return {'Qualified':'green','Follow-up':'amber','WhatsApp Details':'purple','New':'blue','Not Interested':'red','No Answer':'gray','Wrong Number':'red'}[s]||'gray'}
function totals(){const qualified=state.leads.filter(l=>l.status==='Qualified').length,sales=state.leads.filter(l=>l.sale>0),saleValue=sales.reduce((a,l)=>a+l.sale,0),received=sales.reduce((a,l)=>a+l.payment,0),rate=commissionRate(),earned=sales.reduce((a,l)=>a+l.payment*rate,0),paid=sales.reduce((a,l)=>a+l.commissionPaid,0);return {qualified,sales:sales.length,saleValue,received,rate,earned,paid,pending:Math.max(0,earned-paid),calls:state.leads.filter(l=>l.lastCall).length}};
function card(title,value,sub){return `<div class="stat"><span>${title}</span><strong>${value}</strong><small>${sub}</small></div>`}
function leadRows(list=state.leads){return list.map(l=>`<tr><td><b>${esc(l.business)}</b><small>${l.id} · ${esc(l.location)}</small></td><td>${esc(l.contact||'—')}<small>${esc(l.phone)}</small></td><td><span class="pill ${statusClass(l.status)}">${esc(l.status)}</span></td><td>${l.followup?new Date(l.followup).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—'}</td><td>${l.sale?money(l.sale):'—'}</td><td><button class="link" onclick="openLead('${l.id}')">Open</button></td></tr>`).join('')||`<tr><td colspan="6" class="empty">No leads found.</td></tr>`}
function dashboard(){const t=totals();return `<section class="stats">${card('Assigned Leads',state.batch.assigned,`Batch · ${state.batch.start} to ${state.batch.end}`)}${card('Calls Made',t.calls,`${state.leads.length?Math.round(t.calls/state.leads.length*100):0}% tracked`)}${card('Qualified Leads',t.qualified,`${Math.round(t.rate*100)}% current slab`)}${card('Sales',t.sales,`${money(t.saleValue)} total`)}</section><section class="grid"><div class="panel"><div class="panelhead"><div><h2>My Leads</h2><p class="muted">Assigned businesses and current status</p></div><button class="secondary small" onclick="showPage('leads')">View all</button></div><div class="tablewrap"><table><thead><tr><th>Lead</th><th>Contact</th><th>Status</th><th>Follow-up</th><th>Sale</th><th></th></tr></thead><tbody>${leadRows(state.leads.slice(0,5))}</tbody></table></div></div>${commissionPanel()}</section><section class="panel"><div class="panelhead"><div><h2>Recent activity</h2><p class="muted">Latest CRM updates</p></div></div><div class="activity">${(state.activity.length?state.activity:[`${state.leads[0].id} marked as Qualified`,`Batch assigned: ${state.batch.assigned} leads`,`Commission slab calculated at ${Math.round(t.rate*100)}%`]).slice(0,6).map((x,i)=>`<p>${esc(x)}<time>${i+1}h ago</time></p>`).join('')}</div></section>`}
function commissionPanel(){const t=totals();return `<div class="panel earnings"><div class="panelhead"><div><h2>Commission</h2><p class="muted">Current batch calculation</p></div></div><div class="rate"><span>Current slab</span><strong>${Math.round(t.rate*100)}%</strong><small>${t.qualified} qualified leads</small></div><div class="money"><span>Commission earned</span><b>${money(t.earned)}</b></div><div class="rows"><div><span>Total sale value</span><b>${money(t.saleValue)}</b></div><div><span>Payment received</span><b>${money(t.received)}</b></div><div><span>Commission paid</span><b>${money(t.paid)}</b></div><div><span>Pending</span><b>${money(t.pending)}</b></div></div><button class="secondary" onclick="showPage('commission')">View commission ledger</button></div>`}
function leadsPage(){return `<section class="panel"><div class="toolbar"><div><h2>My Leads</h2><p class="muted">Only assigned leads are visible to the caller.</p></div><div class="filters"><input id="leadSearch" placeholder="Search business or phone" oninput="renderLeadTable()"><select id="statusFilter" onchange="renderLeadTable()"><option>All statuses</option>${['New','Qualified','Follow-up','WhatsApp Details','Not Interested','No Answer','Wrong Number'].map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="tablewrap"><table><thead><tr><th>Lead</th><th>Contact</th><th>Status</th><th>Follow-up</th><th>Sale</th><th>Action</th></tr></thead><tbody id="leadTableBody">${leadRows()}</tbody></table></div></section>`}
function followupsPage(){const list=state.leads.filter(l=>l.followup);return `<section class="panel"><div class="panelhead"><div><h2>Follow-ups</h2><p class="muted">Scheduled customer callbacks.</p></div></div><div class="follow-grid">${list.map(l=>`<article><div class="row"><span class="pill ${statusClass(l.status)}">${esc(l.status)}</span><b>${new Date(l.followup).toLocaleString('en-IN',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</b></div><h3>${esc(l.business)}</h3><p>${esc(l.notes||'No notes')}</p><button class="secondary small" onclick="openLead('${l.id}')">Open lead</button></article>`).join('')||'<div class="empty">No follow-ups scheduled.</div>'}</div></section>`}
function salesPage(){const sales=state.leads.filter(l=>l.sale>0),t=totals();return `<section class="stats two-wide">${card('Successful Sales',t.sales,'Across this batch')}${card('Total Sale Value',money(t.saleValue),'Actual final sale values')}${card('Payment Received',money(t.received),'Collected by Webefy')}${card('Commission Pending',money(t.pending),'Based on payments received')}</section><section class="panel"><div class="panelhead"><div><h2>Sales Ledger</h2><p class="muted">Lead → sale → payment → commission.</p></div></div><div class="tablewrap"><table><thead><tr><th>Lead</th><th>Sale value</th><th>Payment received</th><th>Rate</th><th>Commission</th><th>Paid</th></tr></thead><tbody>${sales.map(l=>`<tr><td><b>${esc(l.business)}</b><small>${l.id}</small></td><td>${money(l.sale)}</td><td>${money(l.payment)}</td><td>${Math.round(t.rate*100)}%</td><td>${money(l.payment*t.rate)}</td><td>${money(l.commissionPaid)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No sales yet.</td></tr>'}</tbody></table></div></section>`}
function commissionPage(){const t=totals();return `<section class="commission-hero"><div><span>Current commission slab</span><strong>${Math.round(t.rate*100)}%</strong><p>${t.qualified} qualified leads in this batch</p></div><div><span>Earned</span><strong>${money(t.earned)}</strong></div><div><span>Paid</span><strong>${money(t.paid)}</strong></div><div><span>Pending</span><strong>${money(t.pending)}</strong></div></section><section class="grid"><div class="panel"><h2>Slab rules</h2><div class="slab"><b>0–9 qualified</b><strong>10%</strong></div><div class="slab"><b>10–19 qualified</b><strong>15%</strong></div><div class="slab"><b>20+ qualified</b><strong>20%</strong></div><p class="muted note">The applicable batch slab is used for successful sales. Commission is calculated on payment actually received by Webefy.</p></div><div class="panel"><h2>Direct sale pricing</h2><p>Website starts at <b>₹15,000</b>. Caller can negotiate up to a final minimum of <b>₹10,000</b> without permission.</p><p class="muted">Higher final sale value means higher commission at the same slab rate. No sale/payment means no commission.</p></div></section>`}
function settingsPage(){return `<section class="panel"><h2>CRM settings</h2><div class="setting"><span>Current mode</span><b>${state.role==='admin'?'Admin':'Caller'}</b></div><div class="setting"><span>Batch target</span><b>10 qualified leads / 50 leads / 3 days</b></div><div class="setting"><span>Website pricing</span><b>₹15,000 start · ₹10,000 caller floor</b></div><div class="setting"><span>Support</span><b>8109324626</b></div><button class="secondary" onclick="resetDemo()">Reset demo data</button></section>`}
function render(page='dashboard'){const app=$('#app');const titles={dashboard:['Good morning 👋','Track calls, qualified leads, sales and earnings.'],leads:['My Leads','Work only on leads assigned by Webefy.'],followups:['Follow-ups','Never miss a promised callback.'],sales:['Sales','Track actual sale values and payment received.'],commission:['Commission','Transparent batch-based commission calculation.'],settings:['Settings','Demo configuration for the CRM prototype.']};$('#pageTitle').textContent=titles[page][0];$('#pageSub').textContent=titles[page][1];app.innerHTML={dashboard,leads:leadsPage,followups:followupsPage,sales:salesPage,commission:commissionPage,settings:settingsPage}[page]();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));window.currentPage=page;}
function showPage(p){render(p)}
function renderLeadTable(){const q=($('#leadSearch')?.value||'').toLowerCase(),f=$('#statusFilter')?.value||'All statuses';const list=state.leads.filter(l=>(f==='All statuses'||l.status===f)&&(`${l.business} ${l.phone} ${l.id}`.toLowerCase().includes(q)));$('#leadTableBody').innerHTML=leadRows(list)}
function openLead(id){const l=state.leads.find(x=>x.id===id);if(!l)return;$('#modalTitle').textContent=`Edit ${l.id}`;$('#leadId').value=l.id;$('#business').value=l.business;$('#contact').value=l.contact;$('#phone').value=l.phone;$('#category').value=l.category;$('#location').value=l.location;$('#status').value=l.status;$('#followup').value=l.followup;$('#notes').value=l.notes;$('#modal').classList.remove('hidden')}
function newLead(){ $('#modalTitle').textContent='Add Lead';$('#leadForm').reset();$('#leadId').value='';$('#modal').classList.remove('hidden') }
function closeModal(){$('#modal').classList.add('hidden')}
function resetDemo(){if(confirm('Reset all demo CRM data?')){localStorage.removeItem(KEY);location.reload()}}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(b)showPage(b.dataset.page)});
$('#addLeadBtn').onclick=newLead;$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;
$('#roleBtn').onclick=()=>{state.role=state.role==='caller'?'admin':'caller';$('#roleBtn').textContent=state.role==='admin'?'Admin mode':'Caller mode';$('#profileName').textContent=state.role==='admin'?'Webefy Admin':state.user.name;$('#profileRole').textContent=state.role==='admin'?'Administrator':state.user.role;save()};
$('#leadForm').onsubmit=e=>{e.preventDefault();const id=$('#leadId').value||`WF-${String(state.leads.length+1).padStart(3,'0')}`;const old=state.leads.find(l=>l.id===id);const data={id,business:$('#business').value.trim(),contact:$('#contact').value.trim(),phone:$('#phone').value.trim(),category:$('#category').value.trim(),location:$('#location').value.trim(),status:$('#status').value,followup:$('#followup').value,notes:$('#notes').value.trim(),sale:old?.sale||0,payment:old?.payment||0,commissionPaid:old?.commissionPaid||0,created:old?.created||new Date().toISOString().slice(0,10),lastCall:new Date().toISOString()};if(old)Object.assign(old,data);else state.leads.unshift(data);state.activity.unshift(`${id} updated: ${data.status}`);state.activity=state.activity.slice(0,10);save();closeModal();render(window.currentPage)};
window.openLead=openLead;window.showPage=showPage;window.renderLeadTable=renderLeadTable;window.resetDemo=resetDemo;
render();
</script>
</body></html>
                                                                            
