-- Run this ENTIRE thing in Supabase > SQL Editor
-- First delete old broken users if any
drop table if exists public.commission_payments, public.payments, public.sales, public.calls, public.leads, public.batches, public.users cascade;
drop type if exists public.user_role cascade;
drop type if exists public.lead_status cascade;

create extension if not exists pgcrypto;

create type public.user_role as enum ('admin','caller');
create type public.lead_status as enum ('new','connected','follow-up','whatsapp-details','qualified','not interested','no answer','wrong number','won','lost');

create table public.users(
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role public.user_role not null default 'caller',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.batches(
  id bigint generated by default as identity primary key,
  name text not null,
  caller_id bigint references public.users(id) on delete set null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table public.leads(
  id bigint generated by default as identity primary key,
  lead_code text not null unique,
  caller_id bigint references public.users(id) on delete set null,
  batch_id bigint references public.batches(id) on delete set null,
  business_name text not null,
  phone text default '',
  location text default '',
  status public.lead_status not null default 'new',
  qualified boolean not null default false,
  follow_up_at timestamptz,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.calls(
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete restrict,
  status text not null,
  notes text not null default '',
  duration_seconds integer not null default 0,
  called_at timestamptz not null default now()
);

create table public.sales(
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete restrict,
  caller_id bigint not null references public.users(id) on delete restrict,
  sale_value numeric(12,2) not null check(sale_value>=10000),
  stage text not null default 'won',
  created_at timestamptz not null default now()
);

create table public.payments(
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  amount numeric(12,2) not null check(amount>0),
  received_at timestamptz not null default now(),
  note text not null default ''
);

create table public.commission_payments(
  id bigint generated by default as identity primary key,
  caller_id bigint not null references public.users(id) on delete restrict,
  sale_id bigint not null references public.sales(id) on delete restrict,
  amount numeric(12,2) not null check(amount>0),
  status text not null default 'paid',
  paid_at timestamptz not null default now(),
  note text not null default ''
);

-- IMPORTANT: Do NOT insert users here, server.js will seed them with bcryptjs