const express=require('express');const path=require('path');const crypto=require('crypto');const Database=require('better-sqlite3');const cookieParser=require('cookie-parser');const helmet=require('helmet');
const app=express();const PORT=process.env.PORT||3000;const SECRET=process.env.SESSION_SECRET||'change-this-webefy-secret';
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'1mb'}));app.use(cookieParser());app.use(express.static(path.join(__dirname,'public')));
const db=new Database(path.join(__dirname,'webefy.sqlite'));db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','caller')),active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS batches(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,caller_id INTEGER,starts_at TEXT,ends_at TEXT,status TEXT DEFAULT 'active',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(caller_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS leads(id INTEGER PRIMARY KEY AUTOINCREMENT,lead_code TEXT UNIQUE NOT NULL,batch_id INTEGER,caller_id INTEGER,business_name TEXT NOT NULL,contact_name TEXT,phone TEXT,category TEXT,location TEXT,website TEXT,existing_website INTEGER DEFAULT 0,status TEXT DEFAULT 'new',qualified INTEGER DEFAULT 0,follow_up_at TEXT,notes TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(caller_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS calls(id INTEGER PRIMARY KEY AUTOINCREMENT,lead_id INTEGER NOT NULL,user_id INTEGER NOT NULL,status TEXT,notes TEXT,duration_seconds INTEGER DEFAULT 0,called_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(lead_id) REFERENCES leads(id),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,lead_id INTEGER NOT NULL,caller_id INTEGER NOT NULL,sale_value REAL NOT NULL,stage TEXT DEFAULT 'won',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(lead_id) REFERENCES leads(id),FOREIGN KEY(caller_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,sale_id INTEGER NOT NULL,amount REAL NOT NULL,received_at TEXT DEFAULT CURRENT_TIMESTAMP,note TEXT DEFAULT '',FOREIGN KEY(sale_id) REFERENCES sales(id));
CREATE TABLE IF NOT EXISTS commission_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,caller_id INTEGER NOT NULL,sale_id INTEGER,amount REAL NOT NULL,status TEXT DEFAULT 'paid',paid_at TEXT DEFAULT CURRENT_TIMESTAMP,note TEXT DEFAULT '',FOREIGN KEY(caller_id) REFERENCES users(id),FOREIGN KEY(sale_id) REFERENCES sales(id));`);
function hash(p){const salt=crypto.randomBytes(16).toString('hex');const h=crypto.scryptSync(p,salt,64).toString('hex');return `${salt}:${h}`;}function verify(p,s){const [salt,h]=s.split(':');const x=crypto.scryptSync(p,salt,64);return crypto.timingSafeEqual(x,Buffer.from(h,'hex'));}
function token(u){const payload=Buffer.from(JSON.stringify({id:u.id,role:u.role,exp:Date.now()+1000*60*60*12})).toString('base64url');const sig=crypto.createHmac('sha256',SECRET).update(payload).digest('base64url');return payload+'.'+sig;}function auth(req,res,next){try{const t=req.cookies.webefy_session;if(!t) return res.status(401).json({error:'Login required'});const [p,s]=t.split('.');const good=crypto.timingSafeEqual(Buffer.from(s),Buffer.from(crypto.createHmac('sha256',SECRET).update(p).digest('base64url')));const u=JSON.parse(Buffer.from(p,'base64url'));if(!good||u.exp<Date.now())throw 0;req.user=u;next();}catch(e){res.status(401).json({error:'Session expired'});}}function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next();}
function seed(){if(db.prepare('SELECT COUNT(*) c FROM users').get().c===0){const ins=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)');ins.run('Webefy Admin','admin@webefy.in',hash('Admin@123'),'admin');ins.run('Demo Caller','caller@webefy.in',hash('Caller@123'),'caller');}}
seed();
app.post('/api/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(String(req.body.email||'').toLowerCase());if(!u||!verify(String(req.body.password||''),u.password_hash))return res.status(401).json({error:'Invalid email or password'});res.cookie('webefy_session',token(u),{httpOnly:true,sameSite:'lax',secure:false,maxAge:43200000});res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post('/api/logout',(req,res)=>{res.clearCookie('webefy_session');res.json({ok:true})});app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/users',auth,admin,(req,res)=>res.json(db.prepare("SELECT id,name,email,role,active FROM users ORDER BY id DESC").all()));
app.post('/api/users',auth,admin,(req,res)=>{try{const r=req.body;const info=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run(r.name,r.email.toLowerCase(),hash(r.password),r.role==='admin'?'admin':'caller');res.json({id:info.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/leads',auth,(req,res)=>{const q=req.user.role==='admin'?db.prepare(`SELECT l.*,u.name caller_name,b.name batch_name FROM leads l LEFT JOIN users u ON u.id=l.caller_id LEFT JOIN batches b ON b.id=l.batch_id ORDER BY l.id DESC`).all():db.prepare(`SELECT l.*,u.name caller_name,b.name batch_name FROM leads l LEFT JOIN users u ON u.id=l.caller_id LEFT JOIN batches b ON b.id=l.batch_id WHERE l.caller_id=? ORDER BY l.id DESC`).all(req.user.id);res.json(q)});
app.post('/api/leads',auth,admin,(req,res)=>{const r=req.body;const code='WF-'+String((db.prepare('SELECT COALESCE(MAX(id),0)+1 n FROM leads').get().n)).padStart(4,'0');const info=db.prepare(`INSERT INTO leads(lead_code,batch_id,caller_id,business_name,contact_name,phone,category,location,website,existing_website,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(code,r.batch_id||null,r.caller_id||null,r.business_name,r.contact_name||'',r.phone||'',r.category||'',r.location||'',r.website||'',r.existing_website?1:0,r.status||'new',r.notes||'');res.json({id:info.lastInsertRowid,lead_code:code})});
app.patch('/api/leads/:id',auth,(req,res)=>{const l=db.prepare('SELECT * FROM leads WHERE id=?').get(req.params.id);if(!l)return res.status(404).json({error:'Lead not found'});if(req.user.role!=='admin'&&l.caller_id!==req.user.id)return res.status(403).json({error:'Not your lead'});const r=req.body;db.prepare(`UPDATE leads SET status=COALESCE(?,status),qualified=COALESCE(?,qualified),follow_up_at=COALESCE(?,follow_up_at),notes=COALESCE(?,notes),updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(r.status,r.qualified==null?null:(r.qualified?1:0),r.follow_up_at,r.notes,req.params.id);res.json({ok:true})});
app.post('/api/leads/:id/calls',auth,(req,res)=>{const l=db.prepare('SELECT * FROM leads WHERE id=?').get(req.params.id);if(!l||req.user.role!=='admin'&&l.caller_id!==req.user.id)return res.status(403).json({error:'Not allowed'});db.prepare('INSERT INTO calls(lead_id,user_id,status,notes,duration_seconds) VALUES(?,?,?,?,?)').run(l.id,req.user.id,req.body.status||'connected',req.body.notes||'',Number(req.body.duration_seconds||0));if(req.body.status)db.prepare('UPDATE leads SET status=?,notes=CASE WHEN ?<>\'\' THEN ? ELSE notes END,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.body.status,req.body.notes||'',req.body.notes||'',l.id);res.json({ok:true})});
app.get('/api/calls/:leadId',auth,(req,res)=>{const l=db.prepare('SELECT * FROM leads WHERE id=?').get(req.params.leadId);if(!l||req.user.role!=='admin'&&l.caller_id!==req.user.id)return res.status(403).json({error:'Not allowed'});res.json(db.prepare(`SELECT c.*,u.name user_name FROM calls c JOIN users u ON u.id=c.user_id WHERE c.lead_id=? ORDER BY c.id DESC`).all(req.params.leadId))});
app.post('/api/sales',auth,(req,res)=>{const l=db.prepare('SELECT * FROM leads WHERE id=?').get(req.body.lead_id);if(!l||req.user.role!=='admin'&&l.caller_id!==req.user.id)return res.status(403).json({error:'Not allowed'});const callerId=l.caller_id||req.user.id;const qualified=db.prepare('SELECT COUNT(*) c FROM leads WHERE caller_id=? AND qualified=1 AND (batch_id IS ? OR batch_id=?)').get(callerId,l.batch_id,l.batch_id).c;const value=Number(req.body.sale_value);if(!value||value<10000)return res.status(400).json({error:'Minimum sale value is ₹10,000'});const info=db.prepare('INSERT INTO sales(lead_id,caller_id,sale_value) VALUES(?,?,?)').run(l.id,callerId,value);db.prepare("UPDATE leads SET status='won',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(l.id);res.json({id:info.lastInsertRowid,rate:qualified>=20?.20:qualified>=10?.15:.10,qualified})});
app.get('/api/sales',auth,(req,res)=>{const rows=req.user.role==='admin'?db.prepare(`SELECT s.*,l.lead_code,l.business_name,u.name caller_name,(SELECT COALESCE(SUM(amount),0) FROM payments p WHERE p.sale_id=s.id) paid FROM sales s JOIN leads l ON l.id=s.lead_id JOIN users u ON u.id=s.caller_id ORDER BY s.id DESC`).all():db.prepare(`SELECT s.*,l.lead_code,l.business_name,u.name caller_name,(SELECT COALESCE(SUM(amount),0) FROM payments p WHERE p.sale_id=s.id) paid FROM sales s JOIN leads l ON l.id=s.lead_id JOIN users u ON u.id=s.caller_id WHERE s.caller_id=? ORDER BY s.id DESC`).all(req.user.id);res.json(rows)});
app.post('/api/payments',auth,(req,res)=>{const s=db.prepare('SELECT * FROM sales WHERE id=?').get(req.body.sale_id);if(!s||req.user.role!=='admin'&&s.caller_id!==req.user.id)return res.status(403).json({error:'Not allowed'});const amount=Number(req.body.amount);if(amount<=0)return res.status(400).json({error:'Invalid amount'});db.prepare('INSERT INTO payments(sale_id,amount,note) VALUES(?,?,?)').run(s.id,amount,req.body.note||'');res.json({ok:true})});
app.post('/api/commission/pay',auth,admin,(req,res)=>{const s=db.prepare('SELECT * FROM sales WHERE id=?').get(req.body.sale_id);if(!s)return res.status(404).json({error:'Sale not found'});const q=db.prepare('SELECT COUNT(*) c FROM leads WHERE caller_id=? AND qualified=1 AND (batch_id IS ? OR batch_id=?)').get(s.caller_id,db.prepare('SELECT batch_id FROM leads WHERE id=?').get(s.lead_id).batch_id,db.prepare('SELECT batch_id FROM leads WHERE id=?').get(s.lead_id).batch_id).c;const rate=q>=20?.2:q>=10?.15:.1;const received=db.prepare('SELECT COALESCE(SUM(amount),0) n FROM payments WHERE sale_id=?').get(s.id).n;const already=db.prepare('SELECT COALESCE(SUM(amount),0) n FROM commission_payments WHERE sale_id=?').get(s.id).n;const payable=Math.max(0,received*rate-already);if(payable<=0)return res.status(400).json({error:'No commission payable yet'});db.prepare('INSERT INTO commission_payments(caller_id,sale_id,amount) VALUES(?,?,?)').run(s.caller_id,s.id,payable);res.json({paid:payable,rate})});
app.get('/api/dashboard',auth,(req,res)=>{const where=req.user.role==='admin'?'':' WHERE caller_id='+Number(req.user.id);const leads=db.prepare(`SELECT COUNT(*) c FROM leads${where}`).get().c;const qualified=db.prepare(`SELECT COUNT(*) c FROM leads${where}${where?' AND':' WHERE'} qualified=1`).get().c;const sales=db.prepare(`SELECT COUNT(*) c,COALESCE(SUM(sale_value),0) amount FROM sales${req.user.role==='admin'?'':' WHERE caller_id='+Number(req.user.id)}`).get();const paid=db.prepare(`SELECT COALESCE(SUM(cp.amount),0) amount FROM commission_payments cp${req.user.role==='admin'?'':' WHERE cp.caller_id='+Number(req.user.id)}`).get();res.json({leads,qualified,sales:sales.c,saleAmount:sales.amount,commissionPaid:paid.amount,rate:qualified>=20?.2:qualified>=10?.15:.1})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Webefy CRM running at http://localhost:${PORT}`));